import React, { useState } from 'react';
import Head from 'next/head';
import { Button, Form, Row, Col, FloatingLabel } from 'react-bootstrap';

import Header from '../components/Header.tsx';
import Input from '../components/common/Input.tsx';
import Select from '../components/common/Select.tsx';
import Footer from '../components/Footer.tsx';
import Title from '../components/common/Title.tsx';
import AvmGraph from '../components/AvmGraph.tsx';
import ControlledTabs from '../components/Tabs.tsx';

import styles from '../styles/Home.module.css';

export default function Home() {
	const [click, setClick] = useState(false);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<div className={styles.content}>
					{!click && <Title />}
					<div className={click && styles.search_max}>
						<div className={styles.content_search}>
							<Form>
								<Row className="g-2">
									<Col md>
										<FloatingLabel
											controlId="floatingInputGrid"
											label="Property postcode"
										>
											<Input
												className={styles.content_search_input}
												type="text"
												placeholder="e.g CH5 387"
											/>
										</FloatingLabel>
									</Col>
									<Col md>
										<FloatingLabel
											controlId="floatingSelectGrid"
											label="Property type"
										>
											<Select className={styles.content_search_select}>
												<option>Please select</option>
												<option value="Flat">Flat</option>
												<option value="Detached">Detached</option>
												<option value="Semi-Detached">Semi-Detached</option>
												<option value="Terrace">Terrace</option>
											</Select>
										</FloatingLabel>
									</Col>
									<Col md>
										<FloatingLabel
											controlId="floatingSelectGrid"
											label="No. of beds"
										>
											<Select className={styles.content_search_last}>
												<option>Please select</option>
												<option value="1">One</option>
												<option value="2">Two</option>
												<option value="3">Three</option>
											</Select>
										</FloatingLabel>
									</Col>
									<Col md>
										<Button
											variant="danger"
											style={{ width: '100%', height: '100%' }}
											onClick={() => setClick((prev) => !prev)}
										>
											{click ? 'Update' : 'Search'}
										</Button>
									</Col>
								</Row>
							</Form>
						</div>
					</div>
					{click && <ControlledTabs />}
					{!click && <AvmGraph />}
				</div>
			</main>
			<Footer />
		</div>
	);
}
